apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
   type: front-end

spec:
  template:
    metadata:
      name: nginx
      labels:
        app: myapp
    spec:
      containers:
        - name: nginx-controller
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      app: myapp